name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Install numpy
        run: |
          pip install numpy
      - name: Install websockets
        run: |
          pip install websockets
      - name: Install playsound
        run: |
          pip install playsound
      - name: Install simple_term_menu
        run: |
          pip install simple_term_menu
      - name: Install servokit
        run: |
          pip install adafruit-circuitpython-servokit

      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
